version: '3.3'

services:
  db:
    image: mysql:8.0.26
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'shedLock'
      MYSQL_USER: 'shed-lock-test-user-8821'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'aZ3yB3EHAuJMENk'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'MBZx8xQPv9BgyKS'
    ports:
      - '3006:3306'
    expose:
      - '3006'